### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by crspybits** [Wstunes/SwiftyJWT#1]
I tried to build this, but run into:

```
module CCommonCrypto [system] {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h"
    export *
}
```

I do not have Xcode named this way, and am not sure why it would be expected... I'd use your pod otherwise if I could get it to build :).

**Comment by crspybits** [comment]
Actually, I should be more clear:

<img width="1409" alt="screen shot 2018-05-08 at 2 22 43 pm" src="https://user-images.githubusercontent.com/5758762/39781052-564003ea-52cb-11e8-8cb8-56caa7ee3603.png">

**Comment by Wstunes** [comment]
You can try to fix it in this way.
Go to Targets-----Build phases------search paths-----Add $(SRCROOT)
Find the tutorial here.
[Reference](https://www.jianshu.com/p/21f435a045fe)
If the issue exists, try to pod the program to your project and see if the error still exists.

**Comment by andrerinaldi** [comment]
You closed the issue, but actually the solution you wrote about did not solve the problem. The error still persists.
